name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}   

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v6
              with:
                python-version: "3.10"
            
            - name: Install dependencies
              run: pip install ".[build]"
            
            - name: Build executable
              run: pyinstaller --onefile --console --name hive --collect-all rich src/hive/main.py

            - name: Rename executable
              shell: bash
              run: |
                if [ -f dist/hive.exe ]; then
                  mv dist/hive.exe dist/hive-${{ matrix.os }}.exe
                else
                  mv dist/hive dist/hive-${{ matrix.os }}
                fi

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                name: hive_${{ github.ref_name }}_${{ matrix.os }}
                path: dist/hive-${{ matrix.os }}*

    release:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/download-artifact@v4
              with:
                path: dist/
            - uses: softprops/action-gh-release@v2
              with:
                files: dist/**/*

